/**
 * Every Handlebars partial the Stonetop templates include, name → path.
 *
 * Foundry preloads these at init; the test render harness compiles the same map off disk. Keeping
 * one map means a partial can never be reachable in play but missing from a test render.
 */
export const STONETOP_PARTIALS = {
	"stonetop.chat-move-roll":   "systems/stonetop/templates/chat/move-roll.hbs",
	"stonetop.actor-header":     "systems/stonetop/templates/actor/partials/actor-header.hbs",
	"stonetop.roll-mode-picker": "systems/stonetop/templates/actor/partials/roll-mode-picker.hbs",
	"stonetop.roll-pick":        "systems/stonetop/templates/apps/roll-pick.hbs",
	"stonetop.advice-button":    "systems/stonetop/templates/actor/partials/advice-button.hbs",
	"stonetop.actor-stats":      "systems/stonetop/templates/actor/partials/actor-stats.hbs",
	"stonetop.stepper-buttons":  "systems/stonetop/templates/actor/partials/stepper-buttons.hbs",
	"stonetop.actor-attributes": "systems/stonetop/templates/actor/partials/actor-attributes.hbs",
	"stonetop.tab-playbook":           "systems/stonetop/templates/actor/partials/tab-playbook.hbs",
	"stonetop.choice-group-condensed": "systems/stonetop/templates/actor/partials/choice-group-condensed.hbs",
	"stonetop.tab-toolbar-toggle":     "systems/stonetop/templates/actor/partials/tab-toolbar-toggle.hbs",
	"stonetop.introductions-section":  "systems/stonetop/templates/actor/partials/introductions-section.hbs",
	"stonetop.tab-moves":        "systems/stonetop/templates/actor/partials/tab-moves.hbs",
	"stonetop.tab-equipment":    "systems/stonetop/templates/actor/partials/tab-equipment.hbs",
	"stonetop.tab-possessions":  "systems/stonetop/templates/actor/partials/tab-possessions.hbs",
	"stonetop.tab-arcana":       "systems/stonetop/templates/actor/partials/tab-arcana.hbs",
	"stonetop.arcanum-cards":    "systems/stonetop/templates/actor/partials/arcanum-cards.hbs",
	"stonetop.tab-followers":    "systems/stonetop/templates/actor/partials/tab-followers.hbs",
	"stonetop.follower-card":    "systems/stonetop/templates/actor/partials/follower-card.hbs",
	"stonetop.follower-inventory": "systems/stonetop/templates/actor/partials/follower-inventory.hbs",
	"stonetop.outfit-items":       "systems/stonetop/templates/actor/partials/outfit-items.hbs",
	"stonetop.editable-field":   "systems/stonetop/templates/actor/partials/editable-field.hbs",
	"stonetop.editable-rich-block": "systems/stonetop/templates/actor/partials/editable-rich-block.hbs",
	"stonetop.tab-insert":        "systems/stonetop/templates/actor/partials/tab-insert.hbs",
	"stonetop.tab-notes":         "systems/stonetop/templates/actor/partials/tab-notes.hbs",
	"stonetop.selection-chips":   "systems/stonetop/templates/actor/partials/selection-chips.hbs",
	"stonetop.tag-list":         "systems/stonetop/templates/actor/partials/tag-list.hbs",
	"stonetop.selection-input":   "systems/stonetop/templates/actor/partials/selection-input.hbs",
	"stonetop.instinct-section":  "systems/stonetop/templates/actor/partials/instinct-section.hbs",
	"stonetop.move-group":       "systems/stonetop/templates/actor/partials/move-group.hbs",
	"stonetop.move-row":         "systems/stonetop/templates/actor/partials/move-row.hbs",
	"stonetop.move-item":        "systems/stonetop/templates/actor/partials/move-item.hbs",
	"stonetop.move-result-row":  "systems/stonetop/templates/actor/partials/move-result-row.hbs",
	"stonetop.steading-tier-body": "systems/stonetop/templates/actor/partials/steading-tier-body.hbs",
	"stonetop.choice-group":     "systems/stonetop/templates/actor/partials/choice-group.hbs",
	"stonetop.choice-row":       "systems/stonetop/templates/actor/partials/choice-row.hbs",
	"stonetop.improvement-group": "systems/stonetop/templates/actor/partials/improvement-group.hbs",
	"stonetop.steading-improvement-board": "systems/stonetop/templates/actor/partials/steading-improvement-board.hbs",
	"stonetop.steading-improvement-card": "systems/stonetop/templates/actor/partials/steading-improvement-card.hbs",
	"stonetop.steading-statement": "systems/stonetop/templates/actor/partials/steading-statement.hbs",
	"stonetop.steading-improvement-payoff": "systems/stonetop/templates/actor/partials/steading-improvement-payoff.hbs",
	"stonetop.steading-season-box": "systems/stonetop/templates/actor/partials/steading-season-box.hbs",
	"stonetop.steading-turn-step": "systems/stonetop/templates/actor/partials/steading-turn-step.hbs",
	"stonetop.steading-turn-roll": "systems/stonetop/templates/actor/partials/steading-turn-roll.hbs",
	"stonetop.steading-applied-line": "systems/stonetop/templates/actor/partials/steading-applied-line.hbs",
	"stonetop.steading-season-wheel": "systems/stonetop/templates/actor/partials/steading-season-wheel.hbs",
	"stonetop.steading-turnover": "systems/stonetop/templates/actor/partials/steading-turnover.hbs",
	"stonetop.steading-adjustments": "systems/stonetop/templates/actor/partials/steading-adjustments.hbs",
	"stonetop.steading-effect-lines": "systems/stonetop/templates/actor/partials/steading-effect-lines.hbs",
	"stonetop.steading-upkeep": "systems/stonetop/templates/actor/partials/steading-upkeep.hbs",
	"stonetop.steading-moments": "systems/stonetop/templates/actor/partials/steading-moments.hbs",
	"stonetop.choice-section":   "systems/stonetop/templates/actor/partials/lore-section.hbs",
	"stonetop.section-heading":  "systems/stonetop/templates/actor/partials/section-heading.hbs",
	"stonetop.steading-size-pill":      "systems/stonetop/templates/actor/partials/steading-size-pill.hbs",
	"stonetop.steading-stat-panel":      "systems/stonetop/templates/actor/partials/steading-stat-panel.hbs",
	"stonetop.steading-ratings-list":    "systems/stonetop/templates/actor/partials/steading-ratings-list.hbs",
	"stonetop.steading-content-list":    "systems/stonetop/templates/actor/partials/steading-content-list.hbs",
	"stonetop.steading-seasons":         "systems/stonetop/templates/actor/partials/steading-seasons.hbs",
	"stonetop.steading-assets":          "systems/stonetop/templates/actor/partials/steading-assets.hbs",
	"stonetop.steading-coinage":         "systems/stonetop/templates/actor/partials/steading-coinage.hbs",
	"stonetop.steading-places-of-interest": "systems/stonetop/templates/actor/partials/steading-places-of-interest.hbs",
	"stonetop.steading-neighbor-places": "systems/stonetop/templates/actor/partials/steading-neighbor-places.hbs",
	"stonetop.steading-folk-roster":      "systems/stonetop/templates/actor/partials/steading-folk-roster.hbs",
	"stonetop.steading-folk-suggestions": "systems/stonetop/templates/actor/partials/steading-folk-suggestions.hbs",
	"stonetop.section-sub-heading":  "systems/stonetop/templates/actor/partials/section-sub-heading.hbs",
	"stonetop.resource-track":   "systems/stonetop/templates/actor/partials/resource-track.hbs",
	"stonetop.resource-input":   "systems/stonetop/templates/actor/partials/resource-input.hbs",
	"stonetop.outfit-item-row":  "systems/stonetop/templates/actor/partials/outfit-item-row.hbs",
	"stonetop.steading":              "systems/stonetop/templates/actor/steading.hbs",
	"stonetop.move-result-editor":    "systems/stonetop/templates/item/partials/move-result-editor.hbs",
	"stonetop.choices-entry-fields":  "systems/stonetop/templates/item/partials/choices-entry-fields.hbs",
	"stonetop.choice-group-editor":   "systems/stonetop/templates/item/partials/choice-group-editor.hbs",
	"stonetop.playbook-ref-row":      "systems/stonetop/templates/item/partials/playbook-ref-row.hbs",
	"stonetop.arcanum-item-def":      "systems/stonetop/templates/item/partials/arcanum-item-def.hbs",
	"stonetop.arcanum-resource":      "systems/stonetop/templates/item/partials/arcanum-resource.hbs",
	"stonetop.string-list-editor":         "systems/stonetop/templates/item/partials/string-list-editor.hbs",
	"stonetop.follower-selection-field":   "systems/stonetop/templates/item/partials/follower-selection-field.hbs",
	"stonetop.follower-member-editor":     "systems/stonetop/templates/item/partials/follower-member-editor.hbs",
	"stonetop.follower-companion-type":    "systems/stonetop/templates/item/partials/follower-companion-type.hbs",
};
