// Build the GM-locked `wonder-tables` RollTable pack source from Book II's dice tables.
// Usage: node scripts/import/pdf/build-tables.js
// Walks every outline article, qualifies each extracted `table` block (conservative: clean 1..N
// dice tables only), and writes one RollTable JSON per qualifying table to packs/src/wonder-tables/.
// Deterministic ids — they match the @DrawTable links the journal build (annotateTables) emits, so
// the inline "Draw" buttons resolve. Non-qualifying tables stay static in the journal and are flagged.
import { execFileSync } from "child_process";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync, readdirSync } from "fs";
import os from "os";
import path from "path";
import { loadOutline, articleRanges } from "./outline.js";
import { extractArticle } from "./layout.js";
import { loadArticlePages } from "./load.js";
import { annotateTables, toRollTableDoc, TABLE_PACK } from "./tables.js";
import { toSlug } from "../../../src/utils/slug.js";

const PDF = process.env.BOOK_PDF ?? "helper/Book_II_-_The_Wider_World_and_Other_Wonders.pdf";
const OUT = `packs/src/${TABLE_PACK}`;
const REVIEW = "helper/wonder-tables-review.md"; // human-readable list of tables left static

function totalPages() {
	const out = execFileSync("mutool", ["info", PDF], { encoding: "utf8" });
	return Number((out.match(/Pages:\s*(\d+)/) || [])[1] || 302);
}

const ranges = articleRanges(loadOutline(PDF), totalPages());
const tmp = mkdtempSync(path.join(os.tmpdir(), "ww-tbl-"));
mkdirSync(OUT, { recursive: true });
// rebuild fresh, but leave the arcana- tables (owned by build-arcana --write-minor) in place.
for (const f of readdirSync(OUT).filter((n) => n.endsWith(".json") && !n.startsWith("arcana-"))) rmSync(path.join(OUT, f));

const flags = [];
const review = []; // { title, skipped[] } for the review file
let written = 0, skippedCount = 0;

for (const [ai, r] of ranges.entries()) {
	const slug = toSlug(r.title);
	let art;
	try {
		const { pages, pageRules, pageImages } = loadArticlePages(PDF, r, { imgDir: tmp, imgPrefix: slug });
		art = extractArticle(pages, { title: r.title, pageRules, pageImages });
	} catch (e) { flags.push(`! ${r.title}: load failed — ${e.message}`); continue; }

	const { tables, skipped } = annotateTables(art, { slug, title: r.title });
	for (const [ti, block] of tables.entries()) {
		const doc = toRollTableDoc(block, { sort: (ai + 1) * 1000 + ti });
		writeFileSync(path.join(OUT, `${slug}-${ti}.json`), JSON.stringify(doc, null, 2) + "\n");
		written++;
	}
	skippedCount += skipped.length;
	if (skipped.length) { flags.push(`? ${r.title}: ${skipped.length} table(s) left static`); review.push({ title: r.title, skipped }); }
}
rmSync(tmp, { recursive: true, force: true });

// Write the review file: every table the conservative qualifier left as a static table, with its
// roll cells + first result so it can be eyeballed against the PDF (page numbers via the journal
// entry's "Book — p.N" line). These are NOT lost — they still render in the journal verbatim.
const md = [
	"# Wonder tables — left static (review)",
	"",
	`Generated by \`scripts/import/pdf/build-tables.js\`. ${skippedCount} table(s) across ${review.length} article(s)`,
	"were NOT turned into RollTables because their roll cells don't tile 1..N for a standard die",
	"(misdetected stat blocks, 2d6 tables, multi-column matrices, parse glitches). They still appear",
	"verbatim as static tables in the journal entry. Eyeball each against the book; if one is a real",
	"single-die table, fix the extraction (layout.js) and rebuild.",
	"",
];
for (const { title, skipped } of review) {
	md.push(`## ${title}`, "");
	for (const s of skipped) {
		const where = s.heading ? ` _(under “${s.heading}”)_` : "";
		const lbl = s.header?.label ? ` label=“${s.header.label}”` : "";
		const roll = s.header?.roll ? ` header=${s.header.roll}` : "";
		md.push(`- rolls: \`${s.rolls.join(" | ")}\`${roll}${lbl}${where}`);
		md.push(`  - first result: ${s.firstResult || "(empty)"}`);
	}
	md.push("");
}
writeFileSync(REVIEW, md.join("\n"));

console.log(`\nwrote ${written} RollTable(s) to ${OUT}/  (${skippedCount} table(s) left static)`);
console.log(`review the static tables in ${REVIEW}`);
if (flags.length) console.log(`\n${flags.length} note(s):\n` + flags.join("\n"));
